In [6]:
#!unzip electro.zip

In [7]:
import pandas as pd
import numpy as np
from numpy import genfromtxt


In [8]:
ds = np.array([
       [0,  0],
       [1,  0],
       [2,  0],
       [3,  1],
       [4,  1],
       [5,  0],
       [6,  0],
       [7,  0],
       [8,  1],
       [9,  1],])

In [9]:
ds = ds.astype(int)
ds

array([[0, 0],
       [1, 0],
       [2, 0],
       [3, 1],
       [4, 1],
       [5, 0],
       [6, 0],
       [7, 0],
       [8, 1],
       [9, 1]])

In [ ]:

data_dir = '/astr/sample_data'

train_dir = 'train'

val_dir = 'val'

test_dir = 'test'

test_data_portion = 0.26

val_data_portion = 0.26

nb_images = 20

In [ ]:
import shutil
import os

In [ ]:
def create_directory(dir_name):
    if os.path.exists(dir_name):
        shutil.rmtree(dir_name)
    os.makedirs(dir_name)
    os.makedirs(os.path.join(dir_name, "param0"))
    os.makedirs(os.path.join(dir_name, "param1"))
    os.makedirs(os.path.join(dir_name, "param2"))

In [ ]:
create_directory(train_dir)
create_directory(val_dir)
create_directory(test_dir)

In [ ]:
arr0_img = np.where(ds==0)[0]
arr0_img

array([ 0,  1,  2,  3,  6,  7,  8, 14])

In [ ]:
arr1_img = np.where(ds==1)[0]
arr1_img

array([ 4,  5,  9, 10, 11, 12, 13, 15, 16])

In [ ]:
arr2_img = np.where(ds==2)[0]
arr2_img

array([17, 18, 19, 20])

In [ ]:
 data_dir = '/content/astr/sample_data/'

In [ ]:
#rm -rf /content/val

In [ ]:
for i in range(arr0_img.shape[0]):
    shutil.copy2(os.path.join(data_dir, "00" + str(ds[arr0_img[i],0]) + ".JPG"), 
                os.path.join(train_dir, "param0"))
    shutil.copy2(os.path.join(data_dir, "00" + str(ds[arr0_img[i],0]) + ".JPG"), 
          os.path.join(val_dir, "param0"))
    shutil.copy2(os.path.join(data_dir, "00" + str(ds[arr0_img[i],0]) + ".JPG"), 
          os.path.join(test_dir, "param0"))
    

    
for i in range(arr1_img.shape[0]):
    shutil.copy2(os.path.join(data_dir, "00" + str(ds[arr1_img[i],0]) + ".JPG"), 
                os.path.join(train_dir, "param1"))
    shutil.copy2(os.path.join(data_dir, "00" + str(ds[arr1_img[i],0]) + ".JPG"), 
          os.path.join(val_dir, "param1"))
    shutil.copy2(os.path.join(data_dir, "00" + str(ds[arr1_img[i],0]) + ".JPG"), 
          os.path.join(test_dir, "param1"))
    
    
for i in range(arr2_img.shape[0]):
    shutil.copy2(os.path.join(data_dir, "00" + str(ds[arr2_img[i],0]) + ".JPG"), 
                os.path.join(train_dir, "param2"))
    shutil.copy2(os.path.join(data_dir, "00" + str(ds[arr2_img[i],0]) + ".JPG"), 
          os.path.join(val_dir, "param2"))
    shutil.copy2(os.path.join(data_dir, "00" + str(ds[arr2_img[i],0]) + ".JPG"), 
          os.path.join(test_dir, "param2"))

In [ ]:
!pip  install scipy

In [ ]:
from tensorflow.python.keras.preprocessing.image import ImageDataGenerator
from tensorflow.python.keras.preprocessing import image
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Activation, Dropout, Flatten, Dense
from tensorflow.python.keras.applications import VGG16
from tensorflow.python.keras.optimizers import Adam
import matplotlib.pyplot as plt
#from scipy.misc import toimage
from matplotlib.pyplot import imread
%matplotlib inline

In [ ]:
train_datagen = ImageDataGenerator(rescale=1. / 255,
                                  rotation_range=40,
                                  width_shift_range=0,
                                  height_shift_range=0,
                                  zoom_range=0.5,
                                  #horizontal_flip=True,
                                  #vertical_flip=True,
                                  fill_mode='constant',cval=255)

In [ ]:
image_file_name = train_dir + '/param2/0055.JPG'
img = image.load_img(image_file_name, target_size=(150, 150))


In [ ]:
batch_size = 64

In [ ]:
x = image.img_to_array(img)
x = x.reshape((1,) + x.shape)
i = 0
for batch in train_datagen.flow(x, batch_size=1):
    plt.figure(i)
    imgplot = plt.imshow(image.array_to_img(batch[0]))
    i += 1
    if i % 4 == 0:
        break


In [ ]:

img_width, img_height = 150, 150

input_shape = (img_width, img_height, 3)

batch_size = 64

nb_train_samples = 1000

nb_validation_samples = 300

nb_test_samples = 300

In [ ]:
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='categorical')

In [ ]:
test_datagen = ImageDataGenerator(rescale=1. / 255)

In [ ]:
val_generator = test_datagen.flow_from_directory(
    val_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='categorical')

In [ ]:
test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='categorical')

In [ ]:
vgg16_net = VGG16(weights='imagenet', include_top=False, input_shape=(150, 150, 3))

W0706 14:04:13.204061 140431433766784 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


58892288/58889256 [==============================] - 1s 0us/step


In [ ]:
vgg16_net.trainable = False

In [ ]:
vgg16_net.summary()

Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 150, 150, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 150, 150, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 150, 150, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 75, 75, 64)        0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 75, 75, 128)       73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 75, 75, 128)       147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 37, 37, 128)       0     

In [ ]:
model = Sequential()
# Добавляем в модель сеть VGG16 вместо слоя
model.add(vgg16_net)
model.add(Flatten())
model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(3))
model.add(Activation('sigmoid'))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
vgg16 (Model)                (None, 4, 4, 512)         14714688  
_________________________________________________________________
flatten_1 (Flatten)          (None, 8192)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 256)               2097408   
_________________________________________________________________
activation_2 (Activation)    (None, 256)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 771       
_________________________________________________________________
activation_3 (Activation)    (None, 3)                

In [ ]:
model.compile(loss='categorical_crossentropy',
              optimizer=Adam(), 
              metrics=['accuracy'])

In [ ]:
model.fit_generator(
    train_generator,
    steps_per_epoch=10,
    epochs=10,
    validation_data=val_generator,
    validation_steps=10)

In [ ]:
scores = model.evaluate_generator(test_generator, 10)

In [ ]:
print("Аккуратность на тестовых данных: %.2f%%" % (scores[1]*100))

Аккуратность на тестовых данных: 100.00%


In [ ]:
model.save('w.h5')

In [ ]:
from tensorflow import keras

model2 = keras.models.load_model('w.h5')

W0706 14:57:08.055342 140431433766784 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:97: calling GlorotUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0706 14:57:08.058238 140431433766784 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:97: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [ ]:
model2.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
vgg16 (Model)                (None, 4, 4, 512)         14714688  
_________________________________________________________________
flatten_1 (Flatten)          (None, 8192)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 256)               2097408   
_________________________________________________________________
activation_2 (Activation)    (None, 256)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 771       
_________________________________________________________________
activation_3 (Activation)    (None, 3)                

In [ ]:
scores2 = model2.evaluate_generator(test_generator, 100)

In [ ]:
print("Аккуратность на тестовых данных: %.2f%%" % (scores2[1]*100))

Аккуратность на тестовых данных: 100.00%
